config/routes.rb
Rails.application.routes.draw do
  get "sms/receive"
  post '/sms/receive', to: 'sms#receive'

  root "recipes#index"
  get "up" => "rails/health#show", as: :rails_health_check

  resource :session
  resources :passwords, param: :token

  resources :recipes
  resources :account_requests, only: [:new, :create]

  namespace :admin do
    get "/" => "pages#home", as: :home

    resources :account_requests
    resources :users
    resources :failed_imports, only: :index do
      post :retry, on: :member
    end
  end
end

app/views/layouts/_flash.html.haml
- flash.each do |(kind, message)|
  = tag.div(message, class: "flash flash-#{kind}")

app/views/layouts/_footer.html.haml
%footer
  %p
    2025 &copy; #{link_to "Recipin", root_path}.
    Recipin is small software.
  - if logged_out?
    %p #{link_to "Request an account", new_account_request_path} or #{external_link_to "host your own", :project_homepage}.

app/views/layouts/_head.html.haml
%head
  %meta{ content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type' }/
  %meta{ content: 'width=device-width,initial-scale=1', name: 'viewport' }/
  %title Recipin
  = csrf_meta_tags
  = csp_meta_tag
  = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'

app/views/layouts/_header.html.haml
.header
  %h1= link_to "Recipin", root_path

  %nav
    = link_to "My Recipes", [:recipes] if authenticated?
    = link_to "Admin", admin_home_path if admin?
    = button_to "Log out", session_path, method: :delete if authenticated?

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Recipin" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type' }/
    %meta{ content: 'width=device-width,initial-scale=1', name: 'viewport' }/

    %title Recipin

    = csrf_meta_tags
    = csp_meta_tag

    - %w[variables base forms flash header footer new_action].each do
      = stylesheet_link_tag it, "data-turbo-track": "reload"

  %body{ class: body_classes }
    = render "layouts/header"
    = render "layouts/flash"
    %div= yield
    = render "layouts/footer"

app/views/layouts/sessions.html.haml
!!!
%html.h-full.bg-white
  = render 'layouts/head'
  %body#users-layout.h-full
    .flex.min-h-full.flex-col.justify-center.px-6.pb-12.gap-y-2
      %h2.text-center.text-2xl.font-bold.tracking-tight.text-gray-900
        = icon_for :carrot, size: 'xl', wrapper_class: 'capitalize flex-col gap-y-6', variant: :solid, gap: '2', text: 'Recipin'

      .mx-auto.w-full.max-w-sm
        .text-center.px-10.flex.flex-col.gap-y-3.text-sm.font-semibold= yield :subtitle
        = tag.div(flash[:alert], style: "color:red") if flash[:alert]
        = tag.div(flash[:notice], style: "color:green") if flash[:notice]
        = yield